<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_GuardedRunnable</name>
   <tag></tag>
   <elementGuidId>6a7ea619-1cf5-4e89-b781-34be873133f6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>li:nth-of-type(2) > a[title=&quot;class in org.openqa.selenium.concurrent&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[contains(text(),'GuardedRunnable')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>dc5ad27b-6ba9-48f4-83bf-e2ac3a71e59d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>GuardedRunnable.html</value>
      <webElementGuid>f13a7452-8350-4f81-8df3-2960ea93a014</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>class in org.openqa.selenium.concurrent</value>
      <webElementGuid>5f239945-fbf3-4619-8a88-265ea91d2542</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>classFrame</value>
      <webElementGuid>69d3b8c9-c40e-4dc5-b3ba-939f0993f978</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>GuardedRunnable</value>
      <webElementGuid>141d5ca3-15e4-4f3d-85b1-6e8fdf994d0b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/main[1]/div[@class=&quot;indexContainer&quot;]/section[1]/ul[1]/li[2]/a[1]</value>
      <webElementGuid>290d00d4-e388-4875-91f9-28866bb9f696</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Capabilities/iframe_packageFrame</value>
      <webElementGuid>73e975f8-bdee-4339-9fa9-9ec43b5e3bd6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'GuardedRunnable')]</value>
      <webElementGuid>e8f4d84c-feed-4fff-82e9-68afac5a8793</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ExecutorServices'])[1]/following::a[1]</value>
      <webElementGuid>56a53d9e-e496-4ee4-80b9-c1eb042a595a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Classes'])[1]/following::a[2]</value>
      <webElementGuid>e626e973-01d6-4ae9-a54d-f90b5e8e5da6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='GuardedRunnable']/parent::*</value>
      <webElementGuid>2deafdf4-c728-4f95-b1b1-342256bdfcdc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'GuardedRunnable.html')]</value>
      <webElementGuid>f39988eb-5573-408b-a18a-6d55d4df8755</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/a</value>
      <webElementGuid>9c340aa2-0548-4887-87a3-ba18d4bbd98f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'GuardedRunnable.html' and @title = 'class in org.openqa.selenium.concurrent' and (text() = 'GuardedRunnable' or . = 'GuardedRunnable')]</value>
      <webElementGuid>18ef374e-7383-48af-93b7-1cc9b918d7c6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
