<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Design spotlightDesign spotlight</name>
   <tag></tag>
   <elementGuidId>c41edd5d-5109-4198-82c4-3d8133df96f9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='__a11yId1']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#__a11yId1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>c11a1643-4599-4f1d-8216-396a96ca2693</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>_1QoxDw Qkd66A tYI0Vw o4TrkA YPTJew Qkd66A tYI0Vw lsXp_w Di_DSA cwOZMg zQlusQ uRvRjQ TKO9Uw _7_JWsw</value>
      <webElementGuid>be0f9b22-609e-4125-bc25-05662a7d2685</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>e90bd392-7f98-4730-adbb-9448df43a304</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>7a480d42-48e8-49af-9e2a-2e393cc46190</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>menu</value>
      <webElementGuid>62ed8546-cbfd-4ed4-9cfe-30d3cf0f62c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>fad4e0f7-0b73-42b0-8784-7b1d338846e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>__a11yId1</value>
      <webElementGuid>820c00e3-8f56-49cc-9cc3-5355e5bf8ba6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>__a11yId2</value>
      <webElementGuid>8969375d-6140-44d6-b038-22b8f3d5718a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Design spotlightDesign spotlight</value>
      <webElementGuid>8187eb80-b7d1-4c84-9f21-c48f82cf0d7e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__a11yId1&quot;)</value>
      <webElementGuid>7e7d9156-95b5-400d-9b71-05f38c5149fa</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='__a11yId1']</value>
      <webElementGuid>ad6dbe97-faef-4548-b198-91ab8746e280</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[5]/div/div[2]/div/header/div[3]/nav/ul/li/div/button</value>
      <webElementGuid>9bf9eaff-e26f-4a13-b046-576cb43f90e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Canva home'])[1]/following::button[1]</value>
      <webElementGuid>27af2a15-d85c-4db2-ac9b-647ed971d4ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Skip to main content'])[1]/following::button[2]</value>
      <webElementGuid>28041ccd-e380-4d89-ab40-544a79212c66</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Visual documents'])[1]/preceding::button[1]</value>
      <webElementGuid>84c94648-fc0b-442a-8260-634c629e5b68</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/div/button</value>
      <webElementGuid>643c8537-dfaa-4048-b436-de089943c365</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = '__a11yId1' and (text() = 'Design spotlightDesign spotlight' or . = 'Design spotlightDesign spotlight')]</value>
      <webElementGuid>65fec433-e217-4140-ac87-18e7171b8aa4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
